### ISSUE TITLE
Collect NESO solar forecasts

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/neso-solar-consumer#1]
We would like to start collecting NESO forecast

https://www.neso.energy/data-portal/embedded-wind-and-solar-forecasts/embedded_solar_and_wind_forecast

Rough to do list
- [x] make a new repo
- [x] openclimatefix/neso-solar-consumer#2
- [x] openclimatefix/neso-solar-consumer#4
- [x] openclimatefix/neso-solar-consumer#5
- [x] openclimatefix/neso-solar-consumer#6
- [x] openclimatefix/neso-solar-consumer#7
- [x] openclimatefix/ocf-infrastructure#702

I'ev labelled this as a good first issue, but it is quite big, so we can divide this into parts if easier

**Comment by Seao7** [comment]
Yeah sure, I can start with point #2.

**Comment by shradiphylleia** [comment]
hi @peterdudfield are some issues mentioned here still open for contribution. from what I could understand creating dag airflow is open but someone else was already on it. thanks

**Comment by peterdudfield** [comment]
Feel free to jump in on that. 

Also the release work flow one needs a bit of work

**Comment by shradiphylleia** [comment]
> Also the release work flow one needs a bit of work
are you referring to #7? could you briefly describe what needs to be worked on there. Thanks
